# Generated by Django 6.0.3 on 2026-03-06 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('land_type', models.CharField(choices=[('agricultural', 'Agricultural'), ('commercial', 'Commercial'), ('residential', 'Residential Plot')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('area', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='lands/')),
                ('owner_name', models.CharField(max_length=150)),
                ('owner_phone', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
