# Generated by Django 6.0.3 on 2026-03-09 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_land_area_alter_land_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('source', models.CharField(default='website', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='land',
            name='area',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='land',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='land',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='lands/'),
        ),
        migrations.AlterField(
            model_name='land',
            name='owner_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='land',
            name='owner_phone',
            field=models.CharField(max_length=15),
        ),
    ]
