# Generated by Django 6.0.3 on 2026-03-27 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_land_user_lead_land_alter_land_owner_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='land',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='land',
            name='image',
        ),
        migrations.RemoveField(
            model_name='land',
            name='land_type',
        ),
        migrations.AddField(
            model_name='land',
            name='property_type',
            field=models.CharField(choices=[('plot', 'Plot'), ('farm', 'Farm'), ('commercial', 'Commercial')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='land',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries_sent', to=settings.AUTH_USER_MODEL)),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='myapp.land')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LandImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='lands/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='myapp.land')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='myapp.land')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'land')},
            },
        ),
    ]
