# Generated by Django 6.0.3 on 2026-03-28 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_land_options_remove_land_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land',
            name='property_type',
            field=models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('agricultural', 'Agricultural'), ('plot', 'Plot'), ('farm', 'Farm')], max_length=20),
        ),
    ]
