# Generated by Django 6.0.3 on 2026-04-03 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_land_property_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='land',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
